name: release helm chart

on:
  push:
    tags:
      - "v*"

jobs:
  release-helm-chart:
    name: Release Nocalhost Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Helm tool installer
        uses: Azure/setup-helm@v1
        with:
          version: "v3.6.3"

      - name: Helm plugin installer
        run: |
          helm plugin install https://e.coding.net/coding-public/helm-push

      - name: Add helm repo
        run: |
          helm repo add --username ${{ secrets.CODING_ARTIFACTS_USER }} --password ${{ secrets.CODING_ARTIFACTS_PASS }} nocalhost "https://nocalhost-helm.pkg.coding.net/nocalhost/nocalhost"
          helm repo add --username ${{ secrets.CODING_ARTIFACTS_USER }} --password ${{ secrets.CODING_ARTIFACTS_PASS }} nocalhost-dep "https://nocalhost-helm.pkg.coding.net/nocalhost/helm"

      - name: Change chart version
        env:
          VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          CHART_VERSION=${VERSION/#v/}
          sed -i "s/^appVersion:.*$/appVersion: \"${VERSION}\"/;s/^version:.*$/version: ${CHART_VERSION}/" deployments/chart/Chart.yaml
          sed -i "s/tag:.*$/tag: \"${VERSION}\"/" deployments/chart/values.yaml
          sed -i "s/^appVersion:.*$/appVersion: \"${VERSION}\"/;s/^version:.*$/version: ${CHART_VERSION}/" deployments/dep-chart/Chart.yaml
          sed -i "s/tag:.*$/tag: \"${VERSION}\"/" deployments/dep-chart/values.yaml

      - name: Push to helm repo
        run: |
          helm push deployments/chart nocalhost
          helm push deployments/dep-chart nocalhost-dep
